Output demo.gif

Set Shell zsh
Set TypingSpeed 75ms
Set FontSize 22
Set Width 1800
Set Height 650

Type "nos-cli - NOS News on the command-line"
Sleep 1s
Ctrl+C

Type "nos-cli"
Sleep 500ms
Enter
Sleep 2s

Type "/groning"
Sleep 1s
Enter 2

Set TypingSpeed 325ms
Sleep 1s
Type "jjj"
Set TypingSpeed 75ms

Sleep 2s
Type "b"

Sleep 500ms
Type ":reset"
Enter

Set TypingSpeed 175ms
Sleep 500ms
Type "jjj"
Sleep 3s
